- alias: "Pi Firmware: Notify Mobile Device"
  id: pi_firmware_notify_mobile
  trigger:
    - platform: state
      entity_id: sensor.pi_firmware_monitor
      to: "Update Available"
  action:
    # Phone Notification
    # REPLACE 'notify.mobile_app_REPLACE_ME' with your actual device ID
    - action: notify.REPLACE_WITH_YOUR_DEVICE_ID
      data:
        title: "🚀 Pi Firmware Update Available"
        message: "A new Pi Firmware Update is ready.\n\n**Current:** {{ state_attr('sensor.pi_firmware_monitor', 'current_version') }}\n**Latest:** {{ state_attr('sensor.pi_firmware_monitor', 'latest_version') }}"
        data:
          tag: "pi_update"
          actions:
            - action: "INSTALL_PI_FIRMWARE"
              title: "Install & Reboot"
              destructive: true

    # Dashboard Notification (Persistent)
    - action: persistent_notification.create
      data:
        title: "🚀 Pi Firmware Update"
        message: "A new Pi Firmware Update is ready.\n\n**Installed:** `{{ state_attr('sensor.pi_firmware_monitor', 'current_version') }}`\n**Latest:** `{{ state_attr('sensor.pi_firmware_monitor', 'latest_version') }}`\n\n[Install & Reboot](/config/script/edit/apply_pi_firmware_update_script)"
        notification_id: "pi_firmware_alert"
